[package]
name = "font-kit"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]

[features]
loader-freetype = ["freetype"]
source-fontconfig = ["servo-fontconfig"]

[dependencies]
arrayvec = "0.4"
bitflags = "1.0"
byteorder = "1.2"
euclid = "0.17"
log = "0.4"
lyon_path = "0.10"
memmap = "0.6"

[dependencies.freetype]
path = "../rust-freetype"
optional = true

[dependencies.servo-fontconfig]
version = "0.4"
optional = true

[target.'cfg(target_family = "windows")'.dependencies]
winapi = "0.2"

[target.'cfg(target_family = "windows")'.dependencies.dwrote]
path = "../dwrote-rs"

[target.'cfg(target_os = "macos")'.dependencies.cocoa]
path = "../core-foundation-rs/cocoa"

[target.'cfg(target_os = "macos")'.dependencies.core-foundation]
path = "../core-foundation-rs/core-foundation"

[target.'cfg(target_os = "macos")'.dependencies.core-graphics]
path = "../core-foundation-rs/core-graphics"

[target.'cfg(target_os = "macos")'.dependencies.core-text]
path = "../core-foundation-rs/core-text"
